import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import{Home,MessageSquare,Plus,Bell,User,Search,Heart,Bookmark,Send,Hammer,Paintbrush,Wrench,Droplets,Zap,Ruler,HardHat,BriefcaseBusiness,Store,MapPin,BadgeCheck,Settings,ShieldCheck,Users,ChevronLeft,Camera}from'lucide-react';
import'./styles.css';

const cats=[
['油漆塗裝',Paintbrush,'乳膠漆、批土、特殊漆'],['藝術塗料',Paintbrush,'微水泥、麂皮、礦物塗料'],['泥作磁磚',Hammer,'打底、貼磚、修補'],['防水抓漏',Droplets,'浴室、外牆、屋頂'],['水電工程',Zap,'配線、給排水、燈具'],['木作裝潢',Ruler,'天花、櫃體、隔間'],['統包設計',HardHat,'裝修管理、設計交流'],['材料工具',Wrench,'工具心得、材料評測'],['徵才找工',BriefcaseBusiness,'找師傅、工班、案件'],['材料商',Store,'材料、經銷、通路交流']
];
const seed=[
{id:1,author:'阿哲師傅',role:'油漆師傅',area:'台北',time:'2 小時前',tag:'藝術塗料',title:'微水泥牆面出現細裂，大家會怎麼處理？',body:'完工約三個月，窗角附近出現髮絲裂紋。底層有做網布與底漆，想請教大家通常會局部修補還是整面重做？',likes:128,comments:36,img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80'},
{id:2,author:'承岳工程',role:'統包',area:'桃園',time:'4 小時前',tag:'統包設計',title:'30 坪中古屋翻新，這樣的工序安排大家覺得順嗎？',body:'拆除 → 水電 → 泥作 → 木作 → 油漆 → 地板 → 系統櫃。現場有兩間浴室需要重做防水，工期抓 45 天。',likes:84,comments:19,img:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80'},
{id:3,author:'小陳防水',role:'防水技師',area:'新北',time:'昨天',tag:'防水抓漏',title:'外牆窗框滲水抓漏紀錄',body:'這場最後不是窗框本體，是上方女兒牆裂縫導水下來。分享一下現場判斷方式，希望能幫到剛入行的朋友。',likes:203,comments:42,img:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80'}
];
const A=({n,s=42})=><div className="avatar" style={{width:s,height:s}}>{n.slice(0,1)}</div>;
function Header({title='工域',back,onBack,right}){return <header><div className="headL">{back?<button className="icon" onClick={onBack}><ChevronLeft/></button>:<div className="logo"><Hammer size={18}/></div>}<b>{title}</b></div><div className="headR">{right||<><Search/><Bell/></>}</div></header>}
function Nav({page,setPage}){return <nav>{[['home',Home,'首頁'],['boards',MessageSquare,'討論區'],['create',Plus,'發文'],['notify',Bell,'通知'],['me',User,'我的']].map(([id,I,t])=><button key={id} className={page===id?'on':''} onClick={()=>setPage(id)}><span className={id==='create'?'plus':''}><I size={id==='create'?24:20}/></span><small>{t}</small></button>)}</nav>}
function Card({p,open}){return <article onClick={()=>open&&open(p)}><div className="author"><A n={p.author}/><div className="grow"><b>{p.author} <BadgeCheck size={14} className="check"/></b><small>{p.role} · {p.area} · {p.time}</small></div></div><span className="tag">{p.tag}</span><h3>{p.title}</h3><p>{p.body}</p><img src={p.img}/><div className="stats"><span><Heart/> {p.likes}</span><span><MessageSquare/> {p.comments}</span><i/><Bookmark/><Send/></div></article>}
function HomePage({posts,open}){const[tab,setTab]=useState('推薦');return <><Header/><div className="tabs">{['推薦','最新','熱門','追蹤'].map(x=><button className={tab===x?'on':''} onClick={()=>setTab(x)}>{x}</button>)}</div><section className="hot"><b>熱門話題</b><div className="chips">{['#微水泥','#防水','#油漆','#找師傅','#報價','#工具'].map(x=><span>{x}</span>)}</div></section>{posts.map(p=><Card key={p.id} p={p} open={open}/>)}</>}
function Boards(){return <><Header title="工程討論區"/><main className="pad"><div className="search"><Search size={18}/><input placeholder="搜尋工程分類、主題、師傅"/></div><div className="boardlist">{cats.map(([n,I,d],i)=><div className="board" key={n}><div className="bicon"><I/></div><div className="grow"><b>{n}</b><small>{d}</small></div><strong>{128-i*7}</strong></div>)}</div></main></>}
function Create({publish}){const[t,setT]=useState(''),[b,setB]=useState(''),[c,setC]=useState('油漆塗裝');return <><Header title="發表文章" right={<button className="publish" onClick={()=>publish(t,b,c)}>發佈</button>}/><main className="pad form"><label>選擇分類<select value={c} onChange={e=>setC(e.target.value)}>{cats.map(x=><option>{x[0]}</option>)}</select></label><input value={t} onChange={e=>setT(e.target.value)} placeholder="標題（必填）"/><textarea value={b} onChange={e=>setB(e.target.value)} placeholder="分享施工經驗、提出工程問題，或交流材料工具…"/><div className="upload"><Camera/><b>加入施工照片</b><small>最多 8 張</small></div></main></>}
function Notify(){return <><Header title="通知"/><div className="tabs"><button className="on">全部</button><button>回覆</button><button>按讚</button><button>追蹤</button></div>{[['工域系統','你的文章被設為熱門討論','10 分鐘前'],['阿凱水電','回覆了你的留言','1 小時前'],['承岳工程','開始追蹤你','3 小時前'],['管理員','師傅認證資料已進入審核','昨天']].map(x=><div className="notice"><A n={x[0]}/><div className="grow"><b>{x[0]}</b><p>{x[1]}</p><small>{x[2]}</small></div></div>)}</>}
function Me({posts}){return <><Header title="我的" right={<Settings/>}/><div className="cover"/><div className="profile"><A n="微創思維" s={76}/><div><h2>微創思維 <BadgeCheck size={18}/></h2><p>藝術塗料・微水泥・油漆工程</p><small><MapPin size={13}/> 北部地區</small></div></div><div className="pstats"><div><b>32</b><small>貼文</small></div><div><b>256</b><small>追蹤中</small></div><div><b>1.2k</b><small>粉絲</small></div></div><div className="pbuttons"><button>編輯個人檔案</button><button>我的收藏</button></div>{posts.slice(0,2).map(p=><Card p={p}/>)}</>}
function Detail({p,back}){return <><Header title="貼文詳情" back onBack={back}/><Card p={p}/><section className="comments"><h3>留言 {p.comments}</h3>{[['泥作阿豪','如果窗角是應力裂，建議先確認底層有沒有跟著裂。'],['小偉工程','局部補完色差可能更明顯，我會看現場決定。']].map(x=><div className="comment"><A n={x[0]} s={38}/><div><b>{x[0]}</b><p>{x[1]}</p></div></div>)}</section></>}
function Admin(){return <><Header title="管理後台"/><main className="admin pad">{[['今日貼文','128'],['今日會員','56'],['待審檢舉','8'],['在線人數','342']].map(x=><div className="metric"><small>{x[0]}</small><b>{x[1]}</b><span>↑ 本週成長</span></div>)}<div className="adminfull"><h3>快捷管理</h3><div className="actions"><button><Users/>會員管理</button><button><MessageSquare/>貼文管理</button><button><ShieldCheck/>檢舉審核</button><button><BadgeCheck/>師傅認證</button></div></div></main></>}
function App(){const[page,setPage]=useState('home'),[posts,setPosts]=useState(seed),[sel,setSel]=useState(null);const publish=(t,b,c)=>{if(!t.trim()||!b.trim())return alert('請先輸入標題與內容');setPosts([{id:Date.now(),author:'微創思維',role:'藝術塗料',area:'北部',time:'剛剛',tag:c,title:t,body:b,likes:0,comments:0,img:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80'},...posts]);setPage('home')};if(sel)return <div className="app"><Detail p={sel} back={()=>setSel(null)}/></div>;return <div className="app"><div className="screen">{page==='home'&&<HomePage posts={posts} open={setSel}/>} {page==='boards'&&<Boards/>}{page==='create'&&<Create publish={publish}/>} {page==='notify'&&<Notify/>}{page==='me'&&<Me posts={posts}/>} {page==='admin'&&<Admin/>}</div><Nav page={page} setPage={setPage}/><button className="adminbtn" onClick={()=>setPage('admin')}><ShieldCheck size={18}/></button></div>}
createRoot(document.getElementById('root')).render(<App/>);