import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Home,MessageSquare,Plus,Bell,User,Search,Heart,Bookmark,Send,Hammer,Paintbrush,Wrench,Droplets,Zap,Ruler,HardHat,BriefcaseBusiness,Store,MapPin,BadgeCheck,Settings,ShieldCheck,Users,ChevronLeft,Camera,LogOut,LogIn,UserPlus,X,Image as ImageIcon,Trash2}from'lucide-react';
import'./styles.css';

const cats=[['油漆塗裝',Paintbrush,'乳膠漆、批土、特殊漆'],['藝術塗料',Paintbrush,'微水泥、麂皮、礦物塗料'],['泥作磁磚',Hammer,'打底、貼磚、修補'],['防水抓漏',Droplets,'浴室、外牆、屋頂'],['水電工程',Zap,'配線、給排水、燈具'],['木作裝潢',Ruler,'天花、櫃體、隔間'],['統包設計',HardHat,'裝修管理、設計交流'],['材料工具',Wrench,'工具心得、材料評測'],['徵才找工',BriefcaseBusiness,'找師傅、工班、案件'],['材料商',Store,'材料、經銷、通路交流']];
const seedPosts=[
{id:1,author:'阿哲師傅',role:'油漆師傅',area:'台北',time:'2 小時前',tag:'藝術塗料',title:'微水泥牆面出現細裂，大家會怎麼處理？',body:'完工約三個月，窗角附近出現髮絲裂紋。底層有做網布與底漆，想請教大家通常會局部修補還是整面重做？',likes:128,comments:[{id:1,author:'泥作阿豪',text:'如果窗角是應力裂，建議先確認底層有沒有跟著裂。'},{id:2,author:'小偉工程',text:'局部補完色差可能更明顯，我會看現場決定。'}],img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',liked:false,saved:false},
{id:2,author:'承岳工程',role:'統包',area:'桃園',time:'4 小時前',tag:'統包設計',title:'30 坪中古屋翻新，這樣的工序安排大家覺得順嗎？',body:'拆除 → 水電 → 泥作 → 木作 → 油漆 → 地板 → 系統櫃。現場有兩間浴室需要重做防水，工期抓 45 天。',likes:84,comments:[],img:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',liked:false,saved:false},
{id:3,author:'小陳防水',role:'防水技師',area:'新北',time:'昨天',tag:'防水抓漏',title:'外牆窗框滲水抓漏紀錄',body:'這場最後不是窗框本體，是上方女兒牆裂縫導水下來。分享一下現場判斷方式，希望能幫到剛入行的朋友。',likes:203,comments:[],img:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',liked:false,saved:false}
];
const defaultUser={name:'微創思維',email:'demo@gongyu.tw',password:'123456',role:'藝術塗料',area:'北部地區',bio:'藝術塗料・微水泥・油漆工程',verified:true,isAdmin:true};
const load=(k,fallback)=>{try{const x=localStorage.getItem(k);return x?JSON.parse(x):fallback}catch{return fallback}};
const A=({n,s=42})=><div className="avatar" style={{width:s,height:s}}>{(n||'工').slice(0,1)}</div>;
function Header({title='工域',back,onBack,right}){return <header><div className="headL">{back?<button className="icon" onClick={onBack}><ChevronLeft/></button>:<div className="logo"><Hammer size={18}/></div>}<b>{title}</b></div><div className="headR">{right||<><Search/><Bell/></>}</div></header>}
function Nav({page,setPage}){return <nav>{[['home',Home,'首頁'],['boards',MessageSquare,'討論區'],['create',Plus,'發文'],['notify',Bell,'通知'],['me',User,'我的']].map(([id,I,t])=><button key={id} className={page===id?'on':''} onClick={()=>setPage(id)}><span className={id==='create'?'plus':''}><I size={id==='create'?24:20}/></span><small>{t}</small></button>)}</nav>}
function Card({p,open,toggleLike,toggleSave}){return <article onClick={()=>open&&open(p)}><div className="author"><A n={p.author}/><div className="grow"><b>{p.author} <BadgeCheck size={14} className="check"/></b><small>{p.role} · {p.area} · {p.time}</small></div></div><span className="tag">{p.tag}</span><h3>{p.title}</h3><p>{p.body}</p>{p.img&&<img src={p.img} alt="施工照片"/>}<div className="stats"><button className={p.liked?'activeStat':''} onClick={e=>{e.stopPropagation();toggleLike?.(p.id)}}><Heart fill={p.liked?'currentColor':'none'}/> {p.likes}</button><span><MessageSquare/> {p.comments?.length||0}</span><i/><button className={p.saved?'activeStat':''} onClick={e=>{e.stopPropagation();toggleSave?.(p.id)}}><Bookmark fill={p.saved?'currentColor':'none'}/></button><Send/></div></article>}
function HomePage({posts,open,toggleLike,toggleSave}){const[tab,setTab]=useState('推薦');const list=useMemo(()=>tab==='熱門'?[...posts].sort((a,b)=>b.likes-a.likes):tab==='追蹤'?posts.filter(p=>['阿哲師傅','承岳工程'].includes(p.author)):posts,[tab,posts]);return <><Header/><div className="tabs">{['推薦','最新','熱門','追蹤'].map(x=><button key={x} className={tab===x?'on':''} onClick={()=>setTab(x)}>{x}</button>)}</div><section className="hot"><b>熱門話題</b><div className="chips">{['#微水泥','#防水','#油漆','#找師傅','#報價','#工具'].map(x=><span key={x}>{x}</span>)}</div></section>{list.map(p=><Card key={p.id} p={p} open={open} toggleLike={toggleLike} toggleSave={toggleSave}/>)}</>}
function Boards(){const[q,setQ]=useState('');const filtered=cats.filter(x=>x[0].includes(q)||x[2].includes(q));return <><Header title="工程討論區"/><main className="pad"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜尋工程分類、主題、師傅"/></div><div className="boardlist">{filtered.map(([n,I,d],i)=><div className="board" key={n}><div className="bicon"><I/></div><div className="grow"><b>{n}</b><small>{d}</small></div><strong>{128-i*7}</strong></div>)}</div></main></>}
function Create({publish,user,onNeedLogin}){const[t,setT]=useState(''),[b,setB]=useState(''),[c,setC]=useState('油漆塗裝'),[img,setImg]=useState('');const pick=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2*1024*1024)return alert('圖片請小於 2MB');const r=new FileReader();r.onload=()=>setImg(r.result);r.readAsDataURL(f)};if(!user)return <NeedLogin onLogin={onNeedLogin}/>;return <><Header title="發表文章" right={<button className="publish" onClick={()=>publish(t,b,c,img)}>發佈</button>}/><main className="pad form"><label>選擇分類<select value={c} onChange={e=>setC(e.target.value)}>{cats.map(x=><option key={x[0]}>{x[0]}</option>)}</select></label><input value={t} onChange={e=>setT(e.target.value)} placeholder="標題（必填）"/><textarea value={b} onChange={e=>setB(e.target.value)} placeholder="分享施工經驗、提出工程問題，或交流材料工具…"/><label className="upload"><input type="file" accept="image/*" onChange={pick}/>{img?<img className="preview" src={img} alt="預覽"/>:<><Camera/><b>加入施工照片</b><small>目前版本單張，2MB 以內</small></>}</label>{img&&<button className="clearImg" onClick={()=>setImg('')}><X size={16}/>移除照片</button>}</main></>}
function NeedLogin({onLogin}){return <><Header title="會員功能"/><div className="needLogin"><LogIn size={44}/><h2>登入後才能使用</h2><p>登入後可以發文、留言、收藏與管理自己的工程內容。</p><button onClick={onLogin}>登入 / 註冊</button></div></>}
function Notify({notices}){return <><Header title="通知"/><div className="tabs"><button className="on">全部</button><button>回覆</button><button>按讚</button><button>系統</button></div>{notices.map(x=><div className="notice" key={x.id}><A n={x.from}/><div className="grow"><b>{x.from}</b><p>{x.text}</p><small>{x.time}</small></div></div>)}</>}
function Auth({onDone,onBack,users,setUsers}){const[mode,setMode]=useState('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[pw,setPw]=useState('');const submit=()=>{if(!email||!pw)return alert('請輸入 Email 與密碼');if(mode==='register'){if(!name.trim())return alert('請輸入名稱');if(users.some(u=>u.email===email))return alert('這個 Email 已註冊');const u={name,email,password:pw,role:'工程會員',area:'台灣',bio:'工程交流會員',verified:false,isAdmin:false};setUsers([...users,u]);onDone(u)}else{const u=users.find(u=>u.email===email&&u.password===pw);if(!u)return alert('帳號或密碼錯誤');onDone(u)}};return <><Header title={mode==='login'?'會員登入':'建立帳號'} back onBack={onBack}/><main className="auth pad"><div className="authLogo"><Hammer/><b>工域</b><span>工程人的專業交流社群</span></div>{mode==='register'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="顯示名稱"/>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><input value={pw} onChange={e=>setPw(e.target.value)} placeholder="密碼" type="password"/><button className="primary" onClick={submit}>{mode==='login'?'登入':'註冊並登入'}</button><button className="switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?<><UserPlus size={17}/>還沒有帳號？註冊</>:<><LogIn size={17}/>已經有帳號？登入</>}</button><div className="demoBox">測試管理員：demo@gongyu.tw / 123456</div></main></>}
function Me({posts,user,onLogin,onLogout,onEdit}){if(!user)return <NeedLogin onLogin={onLogin}/>;const mine=posts.filter(p=>p.author===user.name);return <><Header title="我的" right={<Settings/>}/><div className="cover"/><div className="profile"><A n={user.name} s={76}/><div><h2>{user.name} {user.verified&&<BadgeCheck size={18}/>}</h2><p>{user.bio}</p><small><MapPin size={13}/> {user.area}</small></div></div><div className="pstats"><div><b>{mine.length}</b><small>貼文</small></div><div><b>256</b><small>追蹤中</small></div><div><b>1.2k</b><small>粉絲</small></div></div><div className="pbuttons"><button onClick={onEdit}>編輯個人檔案</button><button onClick={onLogout}><LogOut size={15}/> 登出</button></div>{mine.length?mine.map(p=><Card key={p.id} p={p}/>):<div className="empty">你還沒有發表文章</div>}</>}
function EditProfile({user,onSave,onBack}){const[name,setName]=useState(user.name),[role,setRole]=useState(user.role),[area,setArea]=useState(user.area),[bio,setBio]=useState(user.bio);return <><Header title="編輯個人檔案" back onBack={onBack} right={<button className="publish" onClick={()=>onSave({...user,name,role,area,bio})}>儲存</button>}/><main className="pad form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="名稱"/><input value={role} onChange={e=>setRole(e.target.value)} placeholder="職業 / 工種"/><input value={area} onChange={e=>setArea(e.target.value)} placeholder="服務地區"/><textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="自我介紹"/></main></>}
function Detail({p,back,addComment,user,onNeedLogin,toggleLike,toggleSave}){const[text,setText]=useState('');return <><Header title="貼文詳情" back onBack={back}/><Card p={p} toggleLike={toggleLike} toggleSave={toggleSave}/><section className="comments"><h3>留言 {p.comments?.length||0}</h3>{(p.comments||[]).map(x=><div className="comment" key={x.id}><A n={x.author} s={38}/><div><b>{x.author}</b><p>{x.text}</p></div></div>)}</section><div className="commentbar"><input value={text} onChange={e=>setText(e.target.value)} placeholder={user?'新增留言…':'登入後留言'} onFocus={()=>!user&&onNeedLogin()}/><button onClick={()=>{if(!user)return onNeedLogin();if(!text.trim())return;addComment(p.id,text);setText('')}}><Send size={18}/></button></div></>}
function Admin({posts,users,deletePost}){return <><Header title="管理後台"/><main className="admin pad">{[['目前貼文',String(posts.length)],['會員數',String(users.length)],['待審檢舉','0'],['版本','v0.2']].map(x=><div className="metric" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>工域論壇</span></div>)}<div className="adminfull"><h3>貼文管理</h3>{posts.map(p=><div className="adminPost" key={p.id}><div className="grow"><b>{p.title}</b><small>{p.author} · {p.tag}</small></div><button onClick={()=>deletePost(p.id)}><Trash2 size={17}/></button></div>)}</div></main></>}
function App(){const[page,setPage]=useState('home'),[posts,setPosts]=useState(()=>load('gongyu_posts_v2',seedPosts)),[users,setUsers]=useState(()=>load('gongyu_users_v2',[defaultUser])),[user,setUser]=useState(()=>load('gongyu_session_v2',null)),[notices,setNotices]=useState(()=>load('gongyu_notices_v2',[{id:1,from:'工域系統',text:'歡迎來到工域工程論壇 v0.2',time:'剛剛'},{id:2,from:'管理員',text:'會員系統、發文、留言與圖片上傳已開放測試',time:'剛剛'}])),[selId,setSelId]=useState(null);useEffect(()=>localStorage.setItem('gongyu_posts_v2',JSON.stringify(posts)),[posts]);useEffect(()=>localStorage.setItem('gongyu_users_v2',JSON.stringify(users)),[users]);useEffect(()=>localStorage.setItem('gongyu_session_v2',JSON.stringify(user)),[user]);useEffect(()=>localStorage.setItem('gongyu_notices_v2',JSON.stringify(notices)),[notices]);const sel=posts.find(p=>p.id===selId);const goAuth=()=>setPage('auth');const publish=(t,b,c,img)=>{if(!t.trim()||!b.trim())return alert('請先輸入標題與內容');const p={id:Date.now(),author:user.name,role:user.role,area:user.area,time:'剛剛',tag:c,title:t,body:b,likes:0,comments:[],img:img||'',liked:false,saved:false};setPosts([p,...posts]);setNotices([{id:Date.now(),from:'工域系統',text:'你的文章已成功發佈',time:'剛剛'},...notices]);setPage('home')};const patch=(id,fn)=>setPosts(ps=>ps.map(p=>p.id===id?fn(p):p));const toggleLike=id=>patch(id,p=>({...p,liked:!p.liked,likes:p.likes+(p.liked?-1:1)}));const toggleSave=id=>patch(id,p=>({...p,saved:!p.saved}));const addComment=(id,text)=>patch(id,p=>({...p,comments:[...(p.comments||[]),{id:Date.now(),author:user.name,text}]}));const saveProfile=u=>{const old=user.name;setUser(u);setUsers(us=>us.map(x=>x.email===u.email?u:x));setPosts(ps=>ps.map(p=>p.author===old?{...p,author:u.name,role:u.role,area:u.area}:p));setPage('me')};if(sel)return <div className="app"><Detail p={sel} back={()=>setSelId(null)} addComment={addComment} user={user} onNeedLogin={()=>{setSelId(null);goAuth()}} toggleLike={toggleLike} toggleSave={toggleSave}/></div>;return <div className="app"><div className="screen">{page==='home'&&<HomePage posts={posts} open={p=>setSelId(p.id)} toggleLike={toggleLike} toggleSave={toggleSave}/>} {page==='boards'&&<Boards/>}{page==='create'&&<Create publish={publish} user={user} onNeedLogin={goAuth}/>} {page==='notify'&&<Notify notices={notices}/>} {page==='me'&&<Me posts={posts} user={user} onLogin={goAuth} onLogout={()=>{setUser(null);setPage('home')}} onEdit={()=>setPage('edit')}/>} {page==='auth'&&<Auth onDone={u=>{setUser(u);setPage('home')}} onBack={()=>setPage('home')} users={users} setUsers={setUsers}/>} {page==='edit'&&user&&<EditProfile user={user} onSave={saveProfile} onBack={()=>setPage('me')}/>} {page==='admin'&&user?.isAdmin&&<Admin posts={posts} users={users} deletePost={id=>setPosts(ps=>ps.filter(p=>p.id!==id))}/>}</div>{!['auth','edit'].includes(page)&&<Nav page={page} setPage={setPage}/>} {user?.isAdmin&&<button className="adminbtn" onClick={()=>setPage('admin')}><ShieldCheck size={18}/></button>}</div>}
createRoot(document.getElementById('root')).render(<App/>);